//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaCarrito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaVenta
    {
        public int IdListaVenta { get; set; }
        public Nullable<int> FKVenta { get; set; }
        public Nullable<int> FKProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
